version: "3.8"

services:
  backend:
    build: ./vox_legatus
    container_name: vox-legatus-backend
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: vox-legatus-db
    restart: always
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: legatus
      POSTGRES_DB: vox_legatus_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: vox-legatus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt  # Certbot certs storage
      - ./certbot/www:/var/www/certbot   # Challenge files storage
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: vox-legatus-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
