version: "3.8"

services:
  backend:
    build: ./vox_legatus
    container_name: vox-legatus-backend
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: vox-legatus-db
    restart: always
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: legatus
      POSTGRES_DB: vox_legatus_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: vox-legatus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/apps/vox_legatus/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /srv/apps/vox_legatus/certbot/conf:/etc/letsencrypt
      - /srv/apps/vox_legatus/certbot/www:/var/www/certbot
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: vox-legatus-certbot
    volumes:
      - /srv/apps/vox_legatus/certbot/conf:/etc/letsencrypt
      - /srv/apps/vox_legatus/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pgdata: