version: "3.8"

services:
  backend:
    build: ./vox_legatus
    container_name: vox-legatus-backend
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: vox-legatus-db
    restart: always
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: legatus
      POSTGRES_DB: vox_legatus_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: vox-legatus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: vox-legatus-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot

volumes:
  pgdata:
  certbot-etc:
